# These are supported funding model platforms

github: # Replace with your GitHub Sponsors username
custom: # Replace with your funding platform

# Example:
# github: [rbt, YOUR_USERNAME]
# patreon: # Replace with your Patreon username
# open_collective: # Replace with your Open Collective username
# ko_fi: # Replace with your Ko-fi username
# tidelift: # Replace with your Tidelift platform-name/package-name
# community_bridge: # Replace with your Community Bridge project-name
# liberapay: # Replace with your Liberapay username
# issuehunt: # Replace with your IssueHunt username
# otechie: # Replace with your Otechie username
# lfx_crowdfunding: # Replace with your LFX Crowdfunding project-name
# polar: # Replace with your Polar username
# buy_me_a_coffee: # Replace with your Buy Me a Coffee username
# thanks_dev: # Replace with your Thanks.dev username
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
